### ISSUE TITLE
New project name: gradle buildSrcVersions

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/buildSrcVersions#26]
_Context: [buildSrcVersions](https://github.com/jmfayard/buildSrcVersions) is a Gradle plugin that makes it easier to manage your dependencies inside your IDE. It extracts all your dependencies and search for available dependencies updates._

I decided I don't want to be stuck with a bad naming for-ever and that I should better do it now than later.

## Renaming

- The repo is now https://github.com/jmfayard/buildSrcVersions
- The plugin is now called buildSrcVersions
- The task to run is: `$./gradlew buildSrcVersions`
- The extension is now `buildSrcVersions { ... }`

## Update

Juste update the block: `plugins { }`

```diff
plugins {
  id("de.fayard.buildSrcVersions") version $gradlePluginPortalVersion
  // id("jmfayard.github.io.gradle-kotlin-dsl-libs") version "0.2.6"
}
```

![gradlePluginPortalVersion](https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/de.fayard/buildSrcVersions/maven-metadata.xml.svg?label=gradlePluginPortal)

## Before the renaming

- The repo will be `jmfayard/gradle-kotlin-dsl-libs`
- Install with `plugins { id("jmfayard.github.io.gradle-kotlin-dsl-libs") }`
- Run with: `$./gradlew syncLibs`

## Reasons for the change

> There are only two hard things in Computer Science: 
> cache invalidation and naming things. 
> -- Phil Karlton

- `buildSrcVersions` tells what the plugin does: re-generate `buildSrc/.../Versions.kt`. Neither `syncLibs` nor `gradle-kotlin-dsl-libs` does that  😞 .
- 😞  `syncLibs` is way too generic. 
- 😞 `Libs` insists on the wrong thing. Extracting Libs.xxx is done once, searching for new Versions is done many times and is more valuable.
- 😞  No consistency between `syncLibs` and `gradle-kotlin-dsl-libs`.
- 😞  `gradle-kotlin-dsl-libs` is not exactly easy to understand and remember. Heck, even I didn't remember it.
- 😞 It gives the wrong impression that it requires the Kotlin DSL. Something people usually don't know about yet, let alone have upgraded their builds.

## TODOs

- [x] Rename the repo
- [x] Publishing to the gradlePluginPortal the plugin de.fayard.buildSrcVersions version 0.2.6 https://github.com/jmfayard/buildSrcVersions/pull/27
- [x] `Thank you. Your new plugin de.fayard.buildSrcVersions has been submitted for approval by Gradle engineers. The request should be processed within the next 24 hours, at which point you will be contacted via email.`
- [x] Redo the README 
- [x] Document how to migrate here and in the CHANGELOG.
- [x] Edit my previous articles to use the right pluginId.
- [ ] Add a warning in the current version of the plugin to warn of the migration.
- [ ] [Do a Github Code search](https://github.com/search?q=jmfayard.github.io&type=Code) and warn my early adapters of the renaming.

**Comment by jmfayard** [comment]
all done
