### ISSUE TITLE
Polishing versionsOnlyMode

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/buildSrcVersions#67]
Summary of the conversation: 

- [ ] Improve documentation in #77 once this is done
- [x] Find Groovy and Kotlin code that make use of this code convention
- [x] Add `buildSrcVersions.alwaysUpdateVersions()`
- [x] Crash with `named()` on older versions
- [x] Put properties last in the file
- [x] Add option `./gradlew :refreshVersions --update`
- [x] Also display available updates for plugins, see #60 
- [x] Remove duplicates from output
- [x] Use format `version.bcpkix.jdk15on=1.0.0` 
- [x] Use format `version.org.square.retrofit=1.0.0` when dependencies can be grouped
- [x] Use format `version.com.example.group.name=1.0.0` for FQDN
- [x] Display update with `   # \-- available=1.13`
- [x] Remove `gradleCurrentVersion` 
- [x] Task `$ ./gradlew refreshVersions` update "gradle.properties" #69 
- [x] No copy-paste should be needed for "gradle.properties"
- [x] If gradle.properties, just create it
- [x] Refactor the task to use multiple actions

**Comment by vlsi** [comment]
I've added 

```
buildSrcVersions {
   versionsOnlyMode = de.fayard.VersionsOnlyMode.GRADLE_PROPERTIES
   versionsOnlyFile = "ver.properties"
}
```

and executed `./gradlew buildSrcVersions`

It did not generate `ver.properties` file, and the output was as follows:

```
Generated report file build/dependencyUpdates/report.json

> Task :buildSrcVersions
Plugin configuration: {"indent":"  ","renameLibs":"Libs","renameVersions":"Versions","useFqqnFor":[],"versionsOnlyFile":"ver.properties","versionsOnlyMode":"GRADLE_PROPERTIES"}
See documentation at https://github.com/jmfayard/buildSrcVersions/issues/53


== 📋 copy-paste needed! 📋 ==

Copy-paste the snippet below:

from-editorconfig-file# <buildSrcVersions>
from-editorconfig-file# Generated by ./gradle buildSrcVersions
from-editorconfig-file# See https://github.com/jmfayard/buildSrcVersions/issues/54
org_jetbrains_gradle_plugin_idea_ext_gradle_plugin=0.5
com_github_vlsi_stage_vote_release_gradle_plugin=1.17.0
de_fayard_buildsrcversions_gradle_plugin=0.5.0
org_nosphere_apache_rat_gradle_plugin=0.5.0
com_github_vlsi_crlf_gradle_plugin=1.17.0
com_github_spotbugs_gradle_plugin=1.6.10
com_github_vlsi_ide_gradle_plugin=1.17.0
org_sonarqube_gradle_plugin=2.7.1
org_apache_logging_log4j=2.11.1
gradleCurrentVersion=5.5.1
commons_collections=3.2.2
gradleLatestVersion=5.6.2
jcl_over_slf4j=1.7.25
commons_lang=2.6
velocity=1.7
junit=4.12
jdom=1.1.3
from-editorconfig-file
## Available updates ##
#com_github_vlsi_stage_vote_release_gradle_plugin=1.27.0
#org_nosphere_apache_rat_gradle_plugin=0.5.2
#com_github_vlsi_crlf_gradle_plugin=1.27.0
#com_github_spotbugs_gradle_plugin=2.0.0
#com_github_vlsi_ide_gradle_plugin=1.27.0
#org_apache_logging_log4j=2.12.1
#jcl_over_slf4j=1.7.28
#jdom=2.0.2
from-editorconfig-file# </buildSrcVersions>

in the file you configure with something like:

// build.gradle(.kts)
buildSrcVersions {
    versionsOnlyMode = VersionsOnlyMode.GRADLE_PROPERTIES
    versionsOnlyFile = "gradle.properties"
}

See https://github.com/jmfayard/buildSrcVersions/issues/54


        modified:   ver.properties
```

It is not clear what `modified:   ver.properties` mean.

**Comment by jmfayard** [comment]
@vlsi Use `versionsOnlyFile = "gradle.properties"`
And add inside `versionsOnlyFile` wherever you want the block marker

```
# <buildSrcVersions>
# </buildSrcVersions>
```

Then re-run the task

**Comment by vlsi** [comment]
>The plugin does not modify the build unless the versionsOnlyFile exists and has the block.

It would be nice if it prints that, so plugin adopters would know what to do.
Then, in case the file is missing, it is quite safe to just go ahead and create it. What could go wrong?

The number of properties generated seems to be much less than the number of distinct dependencies used in Apache JMeter project.

For instance, for now we have

```
httpasyncclient.version=4.1.4
httpclient.version=4.5.8
httpcore-nio.version=4.4.11
httpcore.version=4.4.11
httpmime.version=4.5.8
```

Nothing of this kind appeared in the output

**Comment by jmfayard** [comment]
> Then, in case the file is missing, it is quite safe to just go ahead and create it. What could go wrong?

Good point, I will improve this.

> The number of properties generated seems to be much less than the number of distinct dependencies used in Apache JMeter project.

Can you post your `report.json` in a gist or something? 

Do you have the kind of warnings described here?

https://github.com/ben-manes/gradle-versions-plugin/issues/334
https://github.com/ben-manes/gradle-versions-plugin/issues/336

**Comment by jmfayard** [comment]
And back to the original question, what do you recommend as a naming convention?

**Comment by vlsi** [comment]
> And back to the original question, what do you recommend as a naming convention?

1) I expect properties to go to `gradle.properties` file (so they could be overridden by `-P` and system env variables)
2) Thus I happen to chose `.version` suffix to distinguish between distinct properties
3) We happen to use "human-readable" names for certain libraries. For instance: https://github.com/apache/jmeter/blob/7148f87e686f5c1276c70cbfe15445e0feef79f7/src/bom/build.gradle.kts#L113-L115
That is we use common `bouncycastle` name.
That seemed to be a nice idea, however it has bitten us already (`jackson-databind` has its own patch version): https://github.com/apache/jmeter/commit/e5a2fe131fb27302d7537bb623ba38ec87f0d50a#diff-e5a8d0cd6ac696339ff5bcbee2507b1cR66

I do not have much data yet, however it seems more or less fine to use `$module.version` naming.
On top of that it could probably make sense to add `propertyNameFor(module: String)` kind of configuration API, so the plugin could
A) recognize that all of `bcmail-jdk15on`, `bcpkix-jdk15on` go under a single property name
B) it could warn user when the versions can't be aligned. E.g. when `bcpkix-jdk15on` has its own patch release, the plugin could suggest to split the property.

**Comment by vlsi** [comment]
4. I don't expect to see `gradleCurrentVersion=5.5.1` property, because it, well, is not very usable

**Comment by jmfayard** [comment]
I already recognize that dependencies from the same group have the same version.
The property is then called `org_jetbrains_kotlin` but I guess `org.jetbrains.kotlin.version` would be better here.
You are right for Gradle current version, it should be a comment to gradleLatestVersion

**Comment by jmfayard** [comment]
About transitive dependencies, see this
https://github.com/ben-manes/gradle-versions-plugin/issues/200

**Comment by vlsi** [comment]
Resolution quirks are caused by my own https://github.com/vlsi/vlsi-release-plugins/tree/master/plugins/checksum-dependency-plugin
a) It denied to resolve "untrusted" dependencies (which is kind of funny and not that funny at the same time)
b) checksum-dependency-plugin does not seem to support `configuration.copy()`. Mr. Ben copies configurations, and it produces names like `:src:components:apiCopy`.

When I disable `checksum-dependency` verification, I get the following.
Did you really mean to sort strings by `.length`? It basically made my day :)

```
# <buildSrcVersions>
# Generated by ./gradle buildSrcVersions
# See https://github.com/jmfayard/buildSrcVersions/issues/54
org_jetbrains_gradle_plugin_idea_ext_gradle_plugin=0.5
com_github_vlsi_stage_vote_release_gradle_plugin=1.17.0
com_github_ben_manes_versions_gradle_plugin=0.25.0
de_fayard_buildsrcversions_gradle_plugin=0.5.0
org_nosphere_apache_rat_gradle_plugin=0.5.0
com_github_vlsi_crlf_gradle_plugin=1.17.0
com_github_spotbugs_gradle_plugin=1.6.10
com_github_vlsi_ide_gradle_plugin=1.17.0
org_bouncycastle_bcmail_jdk15on=1.60
org_bouncycastle_bcpkix_jdk15on=1.60
org_bouncycastle_bcprov_jdk15on=1.60
org_spockframework_spock_core=1.2-groovy-2.4
org_sonarqube_gradle_plugin=2.7.1
org_apache_logging_log4j=2.11.1
geronimo_jms_1_1_spec=1.1.1
gradleCurrentVersion=5.5.1
javax_activation_api=1.2.0
org_apache_ftpserver=1.1.1
commons_collections=3.2.2
gradleLatestVersion=5.6.2
jackson_annotations=2.9.9
org_apache_activemq=5.15.8
org_springframework=4.3.17.RELEASE
xmlgraphics_commons=2.3
mongo_java_driver=2.11.3
jackson_databind=2.9.9.3
javax_activation=none
accessors_smart=1.2
httpasyncclient=4.1.4
rsyntaxtextarea=3.0.2
commons_codec=1.11
commons_dbcp2=2.5.0
commons_jexl3=3.1
commons_lang3=3.8.1
commons_math3=3.6.1
commons_pool2=2.6.0
hamcrest_core=1.3
hamcrest_date=2.0.4
commons_jexl=2.1.1
commons_lang=2.6
commons_text=1.6
httpcore_nio=4.4.11
jackson_core=2.9.9
tika_parsers=none
cglib_nodep=3.2.9
commons_net=3.6
commons_io=2.6
freemarker=2.3.28
groovy_all=none
json_smart=2.3
ph_commons=9.2.1
xercesimpl=none
json_path=2.4.0
mina_core=2.0.19
objenesis=none
org_slf4j=1.7.25
tika_core=1.22
caffeine=2.6.2
httpmime=4.5.8
org_jodd=5.0.6
saxon_he=9.9.1-1
velocity=1.7
xml_apis=none
darcula=none
dnsjava=2.1.8
jcharts=0.7.5
xstream=1.4.11
hsqldb=2.4.1
ph_css=6.1.1
jsoup=1.11.3
jtidy=r938
junit=4.12
rhino=1.7.10
xalan=2.7.2
jdom=1.1.3
mail=1.5.0-b01
bsf=2.4.0
bsh=2.0b6
dec=0.1.2
oro=2.0.8

## Available updates ##
#com_github_vlsi_stage_vote_release_gradle_plugin=1.27.0
#org_nosphere_apache_rat_gradle_plugin=0.5.2
#com_github_vlsi_crlf_gradle_plugin=1.27.0
#com_github_spotbugs_gradle_plugin=2.0.0
#com_github_vlsi_ide_gradle_plugin=1.27.0
#org_bouncycastle_bcmail_jdk15on=1.63
#org_bouncycastle_bcpkix_jdk15on=1.63
#org_bouncycastle_bcprov_jdk15on=1.63
#org_apache_logging_log4j=2.12.1
#org_apache_activemq=5.15.10
#org_springframework=5.1.9.RELEASE
#mongo_java_driver=3.11.0
#rsyntaxtextarea=3.0.3
#commons_codec=1.13
#commons_dbcp2=2.7.0
#commons_lang3=3.9
#commons_pool2=2.7.0
#hamcrest_core=2.1
#hamcrest_date=2.0.5
#commons_text=1.8
#httpcore_nio=4.4.12
#cglib_nodep=3.3.0
#freemarker=2.3.29
#ph_commons=9.3.6
#mina_core=2.1.3
#org_slf4j=1.7.28
#caffeine=2.8.0
#httpmime=4.5.10
#saxon_he=9.9.1-5
#dnsjava=2.1.9
#xstream=1.4.11.1
#hsqldb=2.5.0
#ph_css=6.2.0
#jsoup=1.12.1
#rhino=1.7.11
#jdom=2.0.2
# </buildSrcVersions>
```

**Comment by jmfayard** [comment]
Yes I meant that! #65

**Comment by vlsi** [comment]
> I already recognize that dependencies from the same group have the same version

The values are 


```
org_bouncycastle_bcmail_jdk15on=1.60
org_bouncycastle_bcpkix_jdk15on=1.60
org_bouncycastle_bcprov_jdk15on=1.60
```

I would prefer just

```
bouncycastle=1.60
```

**Comment by jmfayard** [comment]
That's a bug, I will fix it

**Comment by vlsi** [comment]
@jmfayard , could you please clarify what is the expected workflow?

It does print `Available updates`, however how do I use it?
Do you mean I should update versions one by one?
Should I commit the file with "available" versions comment?

I think it would be just fine if the task updated the file with never versions. Then I can either revert or commit the bits I need.

**Comment by jmfayard** [comment]
This feature is new so it probably needs some polishing
But here is what works well for the journal mode that generates Versions.kt
:

1) run the task, it updates the comments but otherwise don't modify/break
your build
2) commit it
3) for each available update, decide if you want to stay at the current
version (then delete the comment) or update (select the right part and
press delete)
4) sync Gradle, run the unit tests, fix what needs to be fixed
5) commit

The point of this workflow is that the plug-in should never break your
build. That's my design goal "first, do not harm"

**Comment by vlsi** [comment]
I see that properties file do not allow to have trailing comments.
However it would probably be slightly better if "update available" line could be co-located with the current declaration.

Then it would probably make sense if there was "just update versions" flag.

Re properties: what do you think if Gradle Plugins were separated from other dependencies?

**Comment by jmfayard** [comment]
I was under the impression that you can't have a trailing comment with the
properties format. I am wrong?

https://en.m.wikipedia.org/wiki/.properties

I'm definitely interested in support for plugins but I won't work it in the
short term.

See issue #60

**Comment by vlsi** [comment]
>I was under the impression that you can't have a trailing comment with the
properties format. I am wrong?

There's a workaround:

```
httpasyncclient=4.1.4
rsyntaxtextarea=3.0.2
# Update available: commons_codec=1.13
commons_codec=1.11
commons_dbcp2=2.5.0
commons_jexl3=3.1
```

**Comment by vlsi** [comment]
> I'm definitely interested in support for plugins but I won't work it in the
short term.

I mean the following: current output in `.properties` format **mixes** regular dependencies and plugins.

I expect the following:

```
# Plugins
...
..

# Dependencies 
...
...
```

**Comment by LouisCAD** [comment]
The `:` character could be replaced by `..`, and the single dots in the artifact names (e.g. `androidx.whatever`) could be leaved as is.
IMHO, that's more readable than dashes and underscores.

**Comment by jmfayard** [comment]
Still some work to do, but after runnning `$ ./gradlew refreshVersions` , `gradle.properties` now look like this:

# Generated by $ ./gradlew refreshVersions
# See https://github.com/jmfayard/buildSrcVersions
version.org.jetbrains.kotlin.plugin.spring.gradle.plugin=1.3.50
version.org.jlleitschuh.gradle.ktlint.gradle.plugin=8.2.0
version.com.github.lkishalmi.gatling.gradle.plugin=3.0.2
                                   # \-- available=3.2.8
version.de.fayard.buildsrcversions.gradle.plugin=0.6.0
version.org.jetbrains.kotlin.jvm.gradle.plugin=1.3.50
version.azure.servicebus.spring.boot.starter=2.1.7
version.micrometer.registry.prometheus=1.2.0
                       # \-- available=1.2.1
version.org.sonarqube.gradle.plugin=2.7.1
version.de.flapdoodle.embed.mongo=2.2.0
version.gatling.charts.highcharts=3.0.0
                  # \-- available=3.2.1
version.kotlintest.runner.junit5=3.4.0
                 # \-- available=3.4.1
version.org.springframework.boot=2.1.7.RELEASE
                 # \-- available=2.1.8.RELEASE
version.ch.qos.logback.contrib=0.1.5
version.jackson.module.kotlin=2.9.9
version.junit.jupiter.engine=5.5.1
             # \-- available=5.5.2
version.org.jetbrains.kotlin=1.3.50
version.spring.security.jwt=1.0.10.RELEASE
version.org.apache.camel=2.24.1
         # \-- available=2.24.2
version.io.rest.assured=4.0.0
        # \-- available=4.1.1
version.kotlin.logging=1.7.6
version.mockwebserver=4.1.0
      # \-- available=4.2.0
version.scala.library=2.12.3
      # \-- available=2.13.0
version.assertj.core=3.13.2
version.io.springfox=2.9.2
version.reactor.test=3.2.11.RELEASE
     # \-- available=3.2.12.RELEASE
version.auth0.utils=0.0.7
version.htmlcleaner=2.22
    # \-- available=2.23
version.io.arrow.kt=0.9.0
version.lucene.core=8.2.0
version.springmockk=1.1.2
version.httpclient=4.5.9
   # \-- available=4.5.10
version.zjsonpatch=0.4.9
version.analytics=2.1.1
version.caffeine=2.8.0
version.jaxb.api=2.3.1
version.ktlint=0.33.0
# \-- available=0.34.2
version.guava=28.0-jre
version.jsoup=1.12.1
version.mockk=1.9.3
version.gson=2.8.5
# Plugin versions
# See https://github.com/jmfayard/buildSrcVersions/issues/60
plugin.org.jetbrains.kotlin.plugin.spring=1.3.50
plugin.org.jlleitschuh.gradle.ktlint=8.2.0
plugin.com.github.lkishalmi.gatling=3.0.2
plugin.de.fayard.buildSrcVersions=0.6.0
plugin.org.jetbrains.kotlin.jvm=1.3.50
plugin.org.springframework.boot=2.1.7.RELEASE
plugin.org.sonarqube=2.7.1

**Comment by LouisCAD** [comment]
I'm curious how it would look for the massive count of androidx, gms (google play services) and firebase artifacts.

**Comment by jmfayard** [comment]
If you have a build.gradle with all of them I can tell you.

Note that there are lots of stupid names in the Android library, so I use a fully qualified domain name for them. The library name alone wouldn't make sense.


```kotlin
/**
     * We don't want to use meaningless generic libs like Libs.core
     *
     * Found many inspiration for bad libs here https://developer.android.com/jetpack/androidx/migrate
     * **/
    val MEANING_LESS_NAMES: List<String> = listOf(
        "common", "core", "core-testing", "testing", "runtime", "extensions",
        "compiler", "migration", "db", "rules", "runner", "monitor", "loader",
        "media", "print", "io", "media", "collection", "gradle", "android"
    )
```
